version: "3.7"

services:
  mercure:
    image: dunglas/mercure:v0.10.4
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'gUkXp2s5v8y/B?E(G+KbPeShVmYq3t6w'
      MERCURE_SUBSCRIBER_JWT_KEY: 'gUkXp2s5v8y/B?E(G+KbPeShVmYq3t6w'
      JWT_KEY: 'gUkXp2s5v8y/B?E(G+KbPeShVmYq3t6w'
      CORS_ALLOWED_ORIGINS: '*'
      PUBLISH_ALLOWED_ORIGINS: '*'
    ports:
      - "3010:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
